export const veridianData = {
    initialResources: ['bioFiber', 'spore'],
    
    // === 하우스 업그레이드 (Lv.0 ~ 10) ===
    houseStages: [
        { name: "덩굴 은신처", desc: "추락한 포드가 거대 덩굴에 뒤덮였습니다. 일단 덩굴을 치워야 합니다.", req: { bioFiber: 10 } },
        { name: "이끼 침대", desc: "폭신한 이끼로 바닥을 깔았습니다. 조금은 살만해졌습니다.", req: { bioFiber: 50, spore: 20 } },
        { name: "나무 구멍 집", desc: "거대 고목의 옹이 구멍을 파내어 안전한 거처를 만들었습니다.", req: { bioFiber: 200, livingWood: 50 } },
        { name: "효모 배양실", desc: "에너지를 얻기 위해 미생물을 키울 전용 공간을 마련했습니다.", req: { spore: 300, yeast: 100 } },
        { name: "생체 발효탑", desc: "건물 전체가 숨을 쉬며 에너지를 순환시키기 시작합니다.", req: { livingWood: 500, bioFuel: 200 } },
        { name: "발광 식물 가로등", desc: "밤에도 기지 주변을 밝게 비출 수 있습니다.", req: { bioFiber: 1000, energy: 50 } },
        { name: "뿌리 기초 공사", desc: "기지가 흔들리지 않게 지면 깊숙이 뿌리를 내립니다.", req: { rootBrick: 200, bioFiber: 2000 } },
        { name: "수액 파이프라인", desc: "나무에서 흐르는 영양분을 효율적으로 운송합니다.", req: { bioFuel: 500, livingWood: 1000 } },
        { name: "키틴질 외벽", desc: "외계 곤충의 껍질 성분을 이용해 벽을 단단하게 보강합니다.", req: { rootBrick: 1000, spore: 5000 } },
        { name: "생체 공명 안테나", desc: "숲의 의식과 연결되어 주변 자원을 감지합니다.", req: { yeast: 2000, bioFuel: 1000 } },
        { name: "거대 식물 기생실", desc: "거대 나무의 수액을 직접 빨아들여 에너지로 전환합니다.", req: { livingWood: 5000, bioFiber: 10000 } },
        { name: "유전자 조작 온실", desc: "초고속 성장이 가능한 변이 식물을 재배합니다.", req: { spore: 20000, energy: 200 } },
        { name: "광합성 유리 돔", desc: "햇빛을 99% 효율로 받아들이는 특수 유기 유리로 지붕을 덮습니다.", req: { rootBrick: 5000, bioFuel: 2000 } },
        { name: "세포벽 강화 외벽", desc: "기지 전체를 단단한 키틴질 장갑으로 감쌉니다.", req: { livingWood: 10000, yeast: 5000 } },
        { name: "뉴런 네트워크 본부", desc: "숲 전체와 통신할 수 있는 생체 컴퓨터를 설치합니다.", req: { spore: 50000, energy: 500 } },
        { name: "변이 세포 배양고", desc: "복잡한 기능을 수행할 변이 세포들을 보관합니다.", req: { mutantCell: 100, bioFiber: 50000 } },
        { name: "효소 정제실", desc: "고농도의 생화학 반응을 제어하기 위한 실험실입니다.", req: { yeast: 20000, bioFuel: 10000 } },
        { name: "생체 전력 저장소", desc: "전기 뱀장어의 원리를 응용한 거대 생체 배터리입니다.", req: { energy: 2000, rootBrick: 10000 } },
        { name: "페로몬 살포 장치", desc: "특수한 향기로 숲의 생명체들을 조종하여 기지를 지킵니다.", req: { pheromone: 50, bioFuel: 20000 } },
        { name: "DNA 분석 센터", desc: "이 행성의 생명 코드를 완벽하게 해독하기 시작합니다.", req: { mutantCell: 500, geneticCode: 10 } },
        { name: "엽록소 가속기", desc: "식물의 광합성 속도를 극한으로 끌어올립니다.", req: { energy: 5000, livingWood: 50000 } },
        { name: "바이오 폴리머 코팅", desc: "우주의 진공 상태를 견딜 수 있는 유기 코팅을 입힙니다.", req: { bioFuel: 50000, mutantCell: 1000 } },
        { name: "포자 추진 엔진 테스트", desc: "폭발적인 가스 포자를 분사하여 추진력을 얻는 실험을 합니다.", req: { spore: 200000, energy: 10000 } },
        { name: "지능형 덩굴 케이블", desc: "신경계처럼 작동하는 덩굴로 기지 전체를 연결합니다.", req: { geneticCode: 50, bioFiber: 100000 } },
        { name: "생태계 조율 장치", desc: "행성 전체의 산소 농도와 기온을 기지 중심으로 맞춥니다.", req: { pheromone: 200, rootBrick: 50000 } },
        { name: "유기체 나노 팩토리", desc: "미세한 박테리아들이 스스로 건물을 수리하고 조립합니다.", req: { mutantCell: 5000, yeast: 100000 } },
        { name: "신경 인터페이스", desc: "파일럿의 뇌와 우주선을 직접 생체 조직으로 연결합니다.", req: { geneticCode: 200, energy: 20000 } },
        { name: "고밀도 생명목 선체", desc: "강철보다 단단하고 스스로 치유되는 생명목으로 선체를 만듭니다.", req: { livingWood: 200000, rootBrick: 100000 } },
        { name: "플라즈마 액낭", desc: "고에너지를 담을 수 있는 유기체 주머니를 장착합니다.", req: { bioFuel: 100000, mutantCell: 10000 } },
        { name: "바이오스피어 코어", desc: "우주선 내부에서 완벽하게 순환되는 생태계를 구축합니다.", req: { biosphereCore: 1, pheromone: 500 } },
        { name: "유전 정보 도서관", desc: "지구의 모든 생명 정보를 데이터화하여 보관합니다.", req: { geneticCode: 1000, mutantCell: 20000 } },
        { name: "대기권 돌파 포자함", desc: "거대한 씨앗 형태의 선체를 최종 점검합니다.", req: { livingWood: 500000, bioFiber: 1000000 } },
        { name: "생체 기압 안정실", desc: "높은 고도에서도 세포가 터지지 않게 압력을 유지합니다.", req: { rootBrick: 200000, energy: 50000 } },
        { name: "항성간 진화 센서", desc: "먼 우주의 생명 신호를 포착하기 위한 유기 안테나입니다.", req: { pheromone: 1000, mutantCell: 50000 } },
        { name: "단백질 추진 탱크", desc: "가장 강력한 유기 에너지를 담을 탱크를 조립합니다.", req: { bioFuel: 300000, yeast: 500000 } },
        { name: "세포 복제 가속기", desc: "우주 여행 중 필요한 유기물을 즉시 복제합니다.", req: { geneticCode: 5000, biosphereCore: 5 } },
        { name: "생명 유지 액체", desc: "승무원들이 동면할 특수한 양수 탱크를 채웁니다.", req: { bioFuel: 500000, mutantCell: 100000 } },
        { name: "광섬유 덩굴 묶음", desc: "빛의 속도로 정보를 전달하는 유기 회로를 완성합니다.", req: { energy: 100000, bioFiber: 2000000 } },
        { name: "최종 진화 정수", desc: "행성의 모든 생명력을 하나의 응축물로 모읍니다.", req: { biosphereCore: 10, pheromone: 5000 } },
        { name: "초공간 씨앗 점화", desc: "우주선이 씨앗처럼 깨어나며 도약을 준비합니다.", req: { geneticCode: 10000, energy: 200000 } },
        { name: "베리디안 탈출 성공", desc: "축하합니다! 당신은 거대한 숲을 떠나 별들의 씨앗이 되었습니다.", req: { biosphereCore: 50, mutantCell: 500000, livingWood: 1000000 }, unlock: "end" }
        // ... (이후 50레벨까지 기획 가능)
    ],

    // === 건물 리스트 (ID 200번대) ===
    buildings: [
        { id: 200, name: "덩굴 채집 캠프", cost: { bioFiber: 15 }, inputs: null, outputs: { bioFiber: 1.0 }, count: 0, reqLevel: 0 },
        { id: 201, name: "자동 가시 낫", cost: { bioFiber: 100, spore: 50 }, inputs: null, outputs: { bioFiber: 5.0 }, count: 0, reqLevel: 1 },
        { id: 202, name: "포자 포집기", cost: { bioFiber: 200 }, inputs: null, outputs: { spore: 2.0 }, count: 0, reqLevel: 1 },
        { id: 203, name: "균사체 인큐베이터", cost: { bioFiber: 500, spore: 200 }, inputs: { bioFiber: 5 }, outputs: { yeast: 2.0 }, count: 0, reqLevel: 2 },
        { id: 204, name: "압축 섬유 분쇄기", cost: { spore: 500, yeast: 50 }, inputs: { bioFiber: 10 }, outputs: { livingWood: 3.0 }, count: 0, reqLevel: 1 },
        { id: 205, name: "미생물 발효조", cost: { livingWood: 200, yeast: 100 }, inputs: { yeast: 5, bioFiber: 10 }, outputs: { bioFuel: 1.5, energy: 10 }, count: 0, reqLevel: 3 },
        { id: 206, name: "생체 태양광 잎", cost: { livingWood: 500, yeast: 200 }, inputs: null, outputs: { energy: 30 }, count: 0, reqLevel: 5 },
        { id: 207, name: "뿌리 벽돌 가마", cost: { spore: 1000, bioFuel: 100 }, inputs: { spore: 20, bioFuel: 5 }, outputs: { rootBrick: 5.0 }, count: 0, reqLevel: 5 },
        { id: 208, name: "심층 뿌리 추출기", cost: { livingWood: 2000, rootBrick: 1000 }, inputs: { energy: 100 }, outputs: { bioFiber: 150.0, spore: 20.0 }, count: 0, reqLevel: 12 },
        { id: 209, name: "고속 균사체 배양기", cost: { yeast: 2000, bioFuel: 1000 }, inputs: { bioFiber: 100 }, outputs: { yeast: 30.0 }, count: 0, reqLevel: 15 },
        { id: 210, name: "대형 생체 발효탑", cost: { livingWood: 5000, rootBrick: 3000 }, inputs: { bioFiber: 200, yeast: 50 }, outputs: { bioFuel: 20.0, energy: 200 }, count: 0, reqLevel: 20 },
        { id: 211, name: "태양광 숲 군집", cost: { bioFuel: 10000, rootBrick: 5000 }, inputs: null, outputs: { energy: 3000 }, count: 0, reqLevel: 25 },
        { id: 212, name: "진화 가속 챔버", cost: { yeast: 10000, spore: 20000 }, inputs: { bioFiber: 500, energy: 1000 }, outputs: { mutantCell: 5.0 }, count: 0, reqLevel: 30 },
        { id: 213, name: "페로몬 정제소", cost: { mutantCell: 5000, bioFuel: 10000 }, inputs: { bioFuel: 200, energy: 500 }, outputs: { pheromone: 10.0 }, count: 0, reqLevel: 32 },
        { id: 214, name: "신경 섬유 직조기", cost: { bioFiber: 100000, mutantCell: 10000 }, inputs: { bioFiber: 1000, energy: 800 }, outputs: { neuralFiber: 20.0 }, count: 0, reqLevel: 35 },
        { id: 215, name: "DNA 나노 프린터", cost: { mutantCell: 50000, neuralFiber: 1000 }, inputs: { mutantCell: 100, energy: 1200 }, outputs: { geneticCode: 5.0 }, count: 0, reqLevel: 38 },
        { id: 216, name: "생체 발광 숲 군집", cost: { geneticCode: 100, pheromone: 500 }, inputs: { pheromone: 10 }, outputs: { energy: 15000 }, count: 0, reqLevel: 41 },
        { id: 217, name: "생태계 심장 반응로", cost: { geneticCode: 1000, mutantCell: 200000 }, inputs: { geneticCode: 10, energy: 5000 }, outputs: { biosphereCore: 1.0 }, count: 0, reqLevel: 44 },
        { id: 218, name: "항성간 씨앗 연구소", cost: { biosphereCore: 10, livingWood: 500000 }, inputs: { livingWood: 5000, geneticCode: 50 }, outputs: { geneticCode: 100.0 }, count: 0, reqLevel: 46 },
        { id: 219, name: "행성 의식 링크 터미널", cost: { biosphereCore: 50, geneticCode: 10000 }, inputs: null, outputs: { energy: 100000, mutantCell: 5000.0 }, count: 0, reqLevel: 48 },
        { id: 220, name: "영원한 포자 저장소", cost: { biosphereCore: 200, mutantCell: 1000000 }, inputs: null, outputs: { spore: 10000.0, bioFiber: 50000.0 }, count: 0, reqLevel: 48 }
    ],

    // === 연구 리스트 ===
    researchList: [
        { id: "v_botany", name: "외계 식물학", desc: "수동 채집 효율 2배 증가", cost: { bioFiber: 100 }, type: 'manual', value: 2, reqResearch: null },
        { id: "v_photosynthesis", name: "광합성 촉진", desc: "생체 태양광 잎 에너지 생산 3배", cost: { yeast: 500, livingWood: 200 }, type: 'building', target: [206], value: 3.0, reqResearch: "v_botany" },
        { id: "v_fermentation", name: "효소 공학", desc: "발효조의 바이오 연료 생산 2배", cost: { yeast: 1000, spore: 500 }, type: 'building', target: [205], value: 2.0, reqResearch: "v_botany" },
        { id: "v_root_hardening", name: "뿌리 강화 기술", desc: "뿌리 벽돌 생산 시설 속도 2.5배", cost: { bioFuel: 500, rootBrick: 100 }, type: 'building', target: [207], value: 2.5, reqResearch: "v_fermentation" },
        { id: "v_enzymatic_boost", name: "효소 활성화", desc: "발효 공정의 바이오 연료 생산량 4배 증가", cost: { yeast: 5000, spore: 10000 }, type: 'building', target: [205, 210], value: 4.0, reqResearch: "v_fermentation" },
        { id: "v_chlorophyll_plus", name: "엽록소 개조", desc: "모든 생체 태양광 시설 에너지 생산 3배", cost: { bioFuel: 10000, livingWood: 5000 }, type: 'building', target: [206, 211], value: 3.0, reqResearch: "v_photosynthesis" },
        { id: "v_waste_compost", name: "폐기물 퇴비화", desc: "모든 가공 시설의 섬유 소모량 40% 감소", cost: { rootBrick: 2000, yeast: 5000 }, type: 'consumption', target: [203, 204, 207, 209], value: 0.6, reqResearch: "v_botany" },
        { id: "v_mutant_growth", name: "변이 가속화", desc: "진화 가속 챔버 및 세포 진화 시설 생산 속도 3배", cost: { mutantCell: 1000, yeast: 10000 }, type: 'building', target: [212, 207], value: 3.0, reqResearch: "v_enzymatic_boost" },
        { id: "v_neural_network", name: "신경망 최적화", desc: "신경 섬유 직조기 가동 및 소모 속도 3.5배 증가", cost: { bioFuel: 20000, mutantCell: 5000 }, type: 'building', target: [214], value: 3.5, reqResearch: "v_mutant_growth" },
        { id: "v_genetic_stability", name: "유전자 안정화", desc: "DNA 프린터의 재료 소모량 50% 감소 (생산 속도 유지)", cost: { geneticCode: 100, pheromone: 200 }, type: 'consumption', target: [208, 215], value: 0.5, reqResearch: "v_neural_network" },
        { id: "v_pheromone_scent", name: "고농축 페로몬", desc: "페로몬 정제소 생산량 4배 증가", cost: { mutantCell: 20000, bioFuel: 50000 }, type: 'building', target: [213], value: 4.0, reqResearch: "v_genetic_stability" },
        { id: "v_forest_glow", name: "심해 발광 유전자", desc: "생체 발광 시설 전력 생산량 3배 증가", cost: { geneticCode: 500, pheromone: 1000 }, type: 'building', target: [206, 211, 216], value: 3.0, reqResearch: "v_chlorophyll_plus" },
        { id: "v_cell_recycling", name: "세포 재사용 기술", desc: "모든 변이 세포 소모 시설의 재료 사용량 40% 감소", cost: { mutantCell: 100000, geneticCode: 1000 }, type: 'consumption', target: [207, 212, 215, 217], value: 0.6, reqResearch: "v_genetic_stability" },
        { id: "v_biosphere_sync", name: "생태계 동기화", desc: "생태계 심장 코어 생산 속도 2.5배 증가", cost: { biosphereCore: 5, pheromone: 2000 }, type: 'building', target: [209, 217], value: 2.5, reqResearch: "v_pheromone_scent" },
        { id: "v_deep_root_opt", name: "뿌리 네트워크 확장", desc: "모든 뿌리 및 덩굴 채집 시설 생산 속도 5배 증가", cost: { livingWood: 100000, rootBrick: 50000 }, type: 'building', target: [200, 201, 208, 220], value: 5.0, reqResearch: "v_waste_compost" },
        { id: "v_interstellar_seed", name: "항성간 씨앗 개량", desc: "항성간 씨앗 연구소 생산 속도 4배 증가", cost: { biosphereCore: 20, geneticCode: 5000 }, type: 'building', target: [218], value: 4.0, reqResearch: "v_biosphere_sync" },
        { id: "v_planetary_mind", name: "행성 의식 통합", desc: "링크 터미널의 에너지 생산 및 자원 획득 2배 증가", cost: { biosphereCore: 50, geneticCode: 10000 }, type: 'building', target: [219], value: 2.0, reqResearch: "v_interstellar_seed" },
        { id: "v_final_evolution", name: "최종 진화 형태", desc: "베리디안 모든 시설의 생산 및 소모 속도 1.3배 증가", cost: { biosphereCore: 100, mutantCell: 500000, bioFiber: 5000000 }, type: 'building', target: [200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220], value: 1.3, reqResearch: "v_planetary_mind" },
        { id: "v_bio_efficiency", name: "생체 에너지 최적화", desc: "베리디안 모든 시설의 전력 소모량 50% 감소", cost: { pheromone: 5000, geneticCode: 2000 }, type: 'energyEff', target: [200,201,203,204,205,207,208,209,210,212,213,214,215,217,218], value: 0.5, reqResearch: "v_cell_recycling" },
        { id: "v_spore_cloud", name: "포자 구름 확산", desc: "모든 포자 및 섬유 채집 효율 4배 증가", cost: { spore: 1000000, bioFiber: 10000000 }, type: 'building', target: [200, 201, 202, 220], value: 4.0, reqResearch: "v_deep_root_opt" }
            ]
};